### ISSUE TITLE
Project directory structure

### ISSUE THREAD

**Issue by danielstjules** [greensock/GreenSock-AS3#1]
Happy to see the project on GitHub! Just had a small suggestion.

In order to support adding these libraries as a GIT submodule to an AS3 project, it might be better if the directory structure was updated to something like GreenSock-AS3/greensock/ rather than GreenSock-AS3/src/com/greensock/

As of right now, if I were to add the project as a submodule, under project-name/src/com/, the libraries would be located at project-name/src/com/GreenSock-AS3/src/com/greensock/ 

With the suggested change, they'd be found at: project-name/src/com/GreenSock-AS3/greensock/ and could be imported with "com.GreenSock-AS3.greensock.LibName;"

As far as I know, there's no way to clone only part of a submodule, so this would make things a bit easier. :)

Thanks!

**Comment by jackdoyle** [comment]
Sorry about the late response. Hm, as I look around it seems like the src/com/... is a pretty common standard to follow and I'm concerned that if I flattened things, it could get awkward if we want to add other things in here like docs, examples, etc. Plus if I remove the "com" from the directory structure, it could trip up some newbies that don't realize the package structure requires that the files be in a "com" folder for publishing. See what I mean? 

Plus, if you are importing things the way you suggested, wouldn't the dash in the GreenSock-AS cause a problem?

**Comment by danielstjules** [comment]
You're right - that does seem to be common convention, my mistake. That said, for extensive documentation and examples, I think they could probably be placed in https://github.com/greensock/GreenSock-AS3/wiki with a link to it from the readme (similar to https://github.com/mbostock/d3/wiki) , but I see your point about new users potentially ignoring the intended structure. And as for the name, I believe package names and namespaces can still contain both underscores and dashes? Anyway, appreciate the reply!
