### ISSUE TITLE
[Question] Porting to haxe

### ISSUE THREAD

**Issue by barisyild** [greensock/GreenSock-AS3#15]
Can I port and publish the library to haxe?

I wanted to ask because I couldn't see any license information in the Project.

**Comment by ROBERT-MCDOWELL** [comment]
ro rust? as this it will help ruffle project.

**Comment by barisyild** [comment]
Ruffle is an emulator, don't need a port for ruffle.

**Comment by jackdoyle** [comment]
Sorry, the code isn't authorized to be ported to a different language.

**Comment by nanjizal** [comment]
To say an algorithm can only be used in language X is not only stupid but evil, is Jackdoyle evil, is he the original creator?

**Comment by barisyild** [comment]
> To say an algorithm can only be used in language X is not only stupid but evil, is Jackdoyle evil, is he the original creator?

I think he is the who wrote the code and also owns the company.

**Comment by jackdoyle** [comment]
Yep, I authored the code and I own GreenSock. 

Are you saying that unless I give everyone the right to copy my code into other languages and use it for their own profit, I'm "evil" and stupid?

**Comment by nanjizal** [comment]
I suspect that EU law and EU perspective is very different from American. The idea that algorithms and pure code is tied to one programming language forever is a very American mindset. It is stupid to tie it to one programming  language when programming languages will not last forever, it is like saying wheels should only be used for Chariots.  Science and maths is not constrained in this way, so I am quite happy to point out this problem with some parts of modern western thinking, and say that in this way your opinions are stupid and from a society progression point of view the limiting is likely an evil aspect related to corporate America.  As an artist I understand the conceptual aspect of art, but if I painted an oil painting I could not complain if another person painted a similar version in pastels. I could complain if someone sold photos of my oil or watercolour paintings. But this is my opinion and am yet to understand your reasoning.

**Comment by nanjizal** [comment]
deleted my comments as they were not positive. You should add a license to your repository. 
I believe that the question was to get MIT or similar style code working for use of feathers. Not for people to profit so much, more because Adobe let down it's developer community and users want to take the good parts from the past and reinvent projects into the future.
