### ISSUE TITLE
about tweenlite ticker

### ISSUE THREAD

**Issue by hellogavin** [greensock/GreenSock-AS3#6]
I compile this code in Flash builder 4.7 will be error in " TweenLite.ticker.addEventListener("tick", tick);" and I check its API cannot find ticker.

**Comment by jackdoyle** [comment]
What version of TweenLite are you using? It sounds like you're using a VERY old version. The ticker was introduced in v12 over a year ago.

**Comment by hellogavin** [comment]
I'm very sorry about this.A very old version was hiding in my project.

**Comment by jackdoyle** [comment]
No problem at all. Glad you figured it out.
