### ISSUE TITLE
Timestamp vs Math.random

### ISSUE THREAD

**Issue by matthaliski** [greensock/GreenSock-AS3#7]
I'm curious if it would be detrimental to swap out the `Math.random()` on line 180 of LoaderItem.as with a timestamp down to the second? It accomplishes a certain randomness which I believe is the goal of that particular line.

The Google Display Network doesn't allow the use of `Math.random()`. They somehow decompile the swf and crawl for that method in particular and block the upload. I've made my own fix and it seems to work fine. But, I feel icky modifying the core.

What are your thoughts? Does it incur any extra overhead?

**Comment by jackdoyle** [comment]
Yes, I think this is doable, sure. Thanks for the suggestion. We'll drop it into the next update.
