### ISSUE TITLE
onTick quick settings

### ISSUE THREAD

**Issue by nuthinking** [greensock/GreenSock-AS3#8]
Is there any particular reason why this is not possible?

TweenLite.to(view, 1, { y:newY, onTick: function (): void { trace("TICK"); }});

The alternative would be to add the listener to the global ticker before and remove it at complete. A bit verbose.

Thanks!

**Comment by jackdoyle** [comment]
There's no such thing as "onTick" - I think you meant "onUpdate" :)

**Comment by nuthinking** [comment]
ops, yes, that will make it! Thanks! ;)
