### ISSUE TITLE
ColorTransformPlugin

### ISSUE THREAD

**Issue by nuthinking** [greensock/GreenSock-AS3#9]
Documentations says to use the following syntax:
// once
TweenPlugin.activate([ColorTransformPlugin]);
// when needed
TweenLite.to(mc, 1, {colorTransform:{tint:0xFF0000, tintAmount:0.5}}); 

But I get: Error #1069: Property colorTransform not found on flash.display.Sprite and there is no default value.

I saw online a syntax without the nested object but then I get "tint not found ....".

Thanks!

**Comment by jackdoyle** [comment]
Hm, I just tested that and it works perfectly. Can you please post a simple FLA that demonstrates the issue in the forums at http://forums.greensock.com so that we can publish on our end and see what's happening? You are using the latest version of all the GreenSock classes, right?
